mongodb/docs-kotlin

examples/src/test/kotlin/DataClassTest.kt, source/examples/generated/DataClassTest.snippet.annotated-data-class.kt, source/examples/generated/DataClassTest.snippet.data-class.kt, source/examples/generated/DataClassTest.snippet.insert-annotated-data-class.kt, source/examples/generated/DataClassTest.snippet.insert-data-class.kt, source/examples/generated/DataClassTest.snippet.recursive-data-class-types-retrieve.kt, source/examples/generated/DataClassTest.snippet.recursive-data-class-types.kt, source/examples/generated/DataClassTest.snippet.retrieve-annotated-data-class.kt, source/examples/generated/DataClassTest.snippet.retrieve-data-class.kt, source/fundamentals/data-formats.txt, source/fundamentals/data-formats/document-data-format-data-class.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29224
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-29224/fundamentals/data-formats/document-data-format-data-class/
=> (DOCSP-29224): Data class document data type 

examples/src/test/kotlin/IndexesBuildersTest.kt, examples/src/test/kotlin/InsertTest.kt, source/examples/generated/IndexesBuildersTest.snippet.ascending-index.kt, source/examples/generated/IndexesBuildersTest.snippet.compound-index.kt, source/examples/generated/IndexesBuildersTest.snippet.descending-index.kt, source/examples/generated/IndexesBuildersTest.snippet.geo2dsphere-index.kt, source/examples/generated/IndexesBuildersTest.snippet.hashed-index.kt, source/examples/generated/IndexesBuildersTest.snippet.text-index.kt, source/fundamentals/builders.txt, source/fundamentals/builders/indexes.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29263
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-29263/fundamentals/builders/indexes/
=> (DOCSP-29263): Indexes Builders page

source/fundamentals/aggregation.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-NNNNN
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/fix_java_oops/fundamentals/aggregation
=> fix java driver mention

examples/src/main/kotlin/usageExamples/watch/Watch.kt, examples/src/main/resources/log4j2.xml, examples/src/test/kotlin/InsertTest.kt, examples/src/test/kotlin/WatchUsageExampleTest.kt, source/examples/generated/Watch.snippet.watch-usage-example.kt, source/examples/generated/WatchUsageExampleTest.snippet.aggregates-watch.kt, source/examples/generated/WatchUsageExampleTest.snippet.basic-watch.kt, source/examples/generated/WatchUsageExampleTest.snippet.collect-change-stream.kt, source/examples/generated/WatchUsageExampleTest.snippet.full-document-changes.kt, source/usage-examples/watch.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29258
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-29258/usage-examples/watch/
=> (DOCSP-29258): Watch Changes Usage Example for Kotlin

examples/src/main/kotlin/usageExamples/bulkWrite/BulkWrite.kt, examples/src/test/kotlin/InsertTest.kt, source/examples/generated/BulkWrite.snippet.bulk-write-usage-example.kt, source/usage-examples/bulkWrite.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29241
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/docsp-29241-bulk-usage/usage-examples/bulkWrite/
Usage Examples > [Perform Bulk Operations page](https://www.mongodb.com/docs/drivers/java/sync/current/usage-examples/bulkWrite/)
=> (DOCSP-29241): Bulk Usage Example page

examples/src/test/kotlin/AuthTest.kt, examples/src/test/kotlin/TimeSeriesTest.kt, source/examples/generated/AuthTest.snippet.aws-connection-string-session-token.kt, source/examples/generated/AuthTest.snippet.aws-connection-string.kt, source/examples/generated/AuthTest.snippet.aws-credential-mongo-cred.kt, source/examples/generated/AuthTest.snippet.aws-credential-session-token.kt, source/examples/generated/AuthTest.snippet.aws-credential.kt, source/examples/generated/AuthTest.snippet.aws-refresh-credentials.kt, source/examples/generated/AuthTest.snippet.default-cred-string.kt, source/examples/generated/AuthTest.snippet.default-mongo-cred.kt, source/examples/generated/AuthTest.snippet.scram-sha-1-cred.kt, source/examples/generated/AuthTest.snippet.scram-sha-1-string.kt, source/examples/generated/AuthTest.snippet.scram-sha-256-cred.kt, source/examples/generated/AuthTest.snippet.scram-sha-256-string.kt, source/examples/generated/AuthTest.snippet.x-509-cred.kt, source/examples/generated/AuthTest.snippet.x-509-string.kt, source/fundamentals.txt, source/fundamentals/auth.txt, source/includes/fundamentals-sections.rst, source/includes/fundamentals/auth-specify.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-29261
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/docsp-29261-auth/fundamentals/auth/
Fundamentals > [Authentication Mechanisms page](https://www.mongodb.com/docs/drivers/java/sync/v4.9/fundamentals/auth/#mongodb-aws)
=> (DOCSP-29261): Authentication 

examples/src/test/kotlin/EnterpriseAuthTest.kt, source/examples/generated/EnterpriseAuthTest.snippet.auth-creds-gssapi.kt, source/examples/generated/EnterpriseAuthTest.snippet.gssapi-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.gssapi-properties-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.java-subject-key.kt, source/examples/generated/EnterpriseAuthTest.snippet.kerberos-subject-provider.kt, source/examples/generated/EnterpriseAuthTest.snippet.ldap-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.ldap-mongo-credential.kt, source/examples/generated/EnterpriseAuthTest.snippet.service-name-key.kt, source/fundamentals.txt, source/fundamentals/enterprise-auth.txt, source/includes/fundamentals/auth-specify.rst
> NOTE: Like the code snippets from the corresponding Java page, 
> enterprise auth code snippets are untested 
JIRA - https://jira.mongodb.org/browse/DOCSP-29270
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/docsp-29270-enterprise-auth/fundamentals/enterprise-auth/
Fundamentals > [Enterprise Authentication Mechanisms page](https://www.mongodb.com/docs/drivers/java/sync/v4.9/fundamentals/enterprise-auth/)
=> (DOCSP-29270): Enterprise Authentication page

README.md
JIRA - no Jira
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/
=> Correct driver name in README

examples/src/test/kotlin/AggregatesBuilderTest.kt, examples/src/test/kotlin/CountTest.kt, examples/src/test/kotlin/FiltersBuildersTest.kt, examples/src/test/kotlin/IndexesBuildersTest.kt, examples/src/test/kotlin/ProjectionsBuildersTest.kt, examples/src/test/kotlin/UpdatesBuildersTest.kt
JIRA - no jira
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/
=> Update builders tests to use get.Config()

source/fundamentals/builders.txt, source/fundamentals/builders/aggregates.txt, source/fundamentals/builders/filters.txt, source/fundamentals/builders/projections.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-NNNNN
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/
=> Apply Rea feedback

examples/src/test/kotlin/MongoClientSettingsTest.kt, source/examples/generated/MongoClientSettingsTest.snippet.chain-order-connection-string.kt, source/examples/generated/MongoClientSettingsTest.snippet.cluster-settings-connection-string.kt, source/examples/generated/MongoClientSettingsTest.snippet.connection-pool-connection-string.kt, source/examples/generated/MongoClientSettingsTest.snippet.example-connection-string.kt, source/examples/generated/MongoClientSettingsTest.snippet.server-settings-connection-string.kt, source/examples/generated/MongoClientSettingsTest.snippet.socket-settings-connection-string.kt, source/examples/generated/MongoClientSettingsTest.snippet.srv-host-connection-string.kt, source/examples/generated/MongoClientSettingsTest.snippet.tls-ssl-connection-string.kt, source/fundamentals/connection/mongoclientsettings.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29267
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/docsp-29267-mongo-client-settings/fundamentals/connection/mongoclientsettings/
=> (DOCSP-29267): Mongo Client Settings page

source/api-documentation.txt, source/fundamentals/connection/network-compression.txt, source/fundamentals/crud/write-operations/bulk.txt, source/fundamentals/data-formats/serialization.txt, source/usage-examples/insertMany.txt, source/usage-examples/watch.txt
Fix broken links reported by Chris Cho
JIRA - no Jira
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/broken-links/
=> Fix broken links

source/faq.txt, source/index.txt, source/issues-and-help.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-30724
[Connection Troubleshooting](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-30724-connection-troubleshooting-page-backport/connection-troubleshooting/) page
[Index](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-30724-connection-troubleshooting-page-backport/) page 
[FAQ ](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-30724-connection-troubleshooting-page-backport/faq/)page
=> Docsp 30724 connection troubleshooting page backport

source/includes/kmongo-description.rst
Miss from merged https://github.com/mongodb/docs-kotlin/pull/92
JIRA - https://jira.mongodb.org/browse/DOCSP-29260
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/no-jira-fix-kmongo-includes/migrate-kmongo/
=> DOCSP-29260: Make KMongo deprecation an important admonition

.github/workflows/vale-tdbx.yml
Fix the trigger for the Vale GH action
=> Fix Vale GH action

source/facets.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-32483
Hey @mongoKart - here's the facet.toml file for the kotlin driver repo.  Please merge if everything looks good!
Thanks,
Sarah
=> DOCSP-32483 programmatic tagging script for the kotlin driver repo

.github/workflows/copy-compat-to-docs-shared.yml
=> 092123: Fix copy-compat-to-docs-shared action

source/compatibility.txt
Note: there's "ERROR UNKNOWN" listed in the build log, but appears to render without issue in staging.
JIRA - None
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/kotlin/v4.11-compat-sharedinclude/compatibility/
=> v4.11 sharedinclude compatibility tables

source/fundamentals/connection/tls.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34060>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-34060-tls-default-seedlist/fundamentals/connection/tls/#enable-tls-ssl
=> DOCSP-34060: mention that using seedlist enables tls

examples/src/test/kotlin/UpdatesBuildersTest.kt, source/examples/generated/UpdatesBuildersTest.snippet.add-to-set-update.kt, source/examples/generated/UpdatesBuildersTest.snippet.combine-update.kt, source/examples/generated/UpdatesBuildersTest.snippet.example-data-class.kt, source/examples/generated/UpdatesBuildersTest.snippet.pull-all-update.kt, source/examples/generated/UpdatesBuildersTest.snippet.pull-update.kt, source/examples/generated/UpdatesBuildersTest.snippet.push-update.kt, source/fundamentals/builders/updates.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34312>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-34312-addtoset-data-class/fundamentals/builders/updates/
=> DOCSP-34312: modify data class to use nested class and update examples

source/faq.txt, source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36039>
Staging:
- [Index](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-36039-link-kt-sdk/#introduction)
- [FAQ](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-36039-link-kt-sdk/faq/#what-is-the-difference-between-the-kotlin-driver-and-the-kotlin-sdk-)
=> DOCSP-36039: surface link to Realm Kotlin SDK

source/fundamentals.txt, source/includes/serialization-libs-gradle-versioned.rst, source/includes/serialization-libs-maven-versioned.rst, source/quick-start.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36113>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-36113-serialization-qs/quick-start/#add-serialization-library-dependencies
=> DOCSP-36113: add serialization pkgs to quickstart

examples/build.gradle.kts, examples/src/test/kotlin/KotlinXSerializationTest.kt, snooty.toml, source/examples/generated/KotlinXSerializationTest.snippet.kserializer-dataclass.kt, source/examples/generated/KotlinXSerializationTest.snippet.kserializer.kt, source/fundamentals/data-formats/serialization.txt, source/quick-start.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35884>
**[Staging](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-35884-custom-serializer/fundamentals/data-formats/serialization/#custom-serializer-example)**
=> DOCSP-35884: custom serializer example

.github/workflows/backport.yml, source/fundamentals.txt, source/fundamentals/builders.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/data-formats.txt, source/index.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/update-operations.txt
* DOCSP-44902 TOC Relabel
* DOCSP-44902 TOC Relabel
* Mike's suggestions
* 'one/many' operation changes
(cherry picked from commit 1144bde00f5ce107638a6d2664abce2ea62aad3b)
Co-authored-by: lindseymoore <71525840+lindseymoore@users.noreply.github.com>
(cherry picked from commit bc41eefcc7e17f719a9a4a50344cdab7d8ad16e1)
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
(cherry picked from commit 39747b227a515b77978fb514b4db2234f568397c)
=> [Backport v5.0] DOCSP-44902 TOC Relabel (#179) (#181) (#182)

.github/workflows/backport.yml, source/fundamentals.txt, source/fundamentals/builders.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/data-formats.txt, source/index.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/update-operations.txt
* DOCSP-44902 TOC Relabel
* DOCSP-44902 TOC Relabel
* Mike's suggestions
* 'one/many' operation changes
(cherry picked from commit 1144bde00f5ce107638a6d2664abce2ea62aad3b)
Co-authored-by: lindseymoore <71525840+lindseymoore@users.noreply.github.com>
(cherry picked from commit bc41eefcc7e17f719a9a4a50344cdab7d8ad16e1)
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
(cherry picked from commit 39747b227a515b77978fb514b4db2234f568397c)
=> [Backport v4.11] Shorten TOC 

source/fundamentals.txt, source/fundamentals/builders.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/data-formats.txt, source/index.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/update-operations.txt
* DOCSP-44902 TOC Relabel
* DOCSP-44902 TOC Relabel
* Mike's suggestions
* 'one/many' operation changes
(cherry picked from commit 1144bde00f5ce107638a6d2664abce2ea62aad3b)
Co-authored-by: lindseymoore <71525840+lindseymoore@users.noreply.github.com>
(cherry picked from commit bc41eefcc7e17f719a9a4a50344cdab7d8ad16e1)
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
(cherry picked from commit 39747b227a515b77978fb514b4db2234f568397c)
=> [Backport v4.10] DOCSP-44902 Shorten TOC

source/fundamentals/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45874>
=> DOCSP-45874: Parallel transactions admonition

.github/pull_request_template.md, .github/workflows/add-netlify-links.yml
=> Add Github action to add Netlify links to PR description

source/usage-examples/watch.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46710>
[At the bottom of the examples section in "Watch for Changes" page](https://deploy-preview-194--docs-kotlin.netlify.app/usage-examples/watch/#example)
=> DOCSP-46710 MongoClient.watch() 404 on Usage Example

source/fundamentals/databases-collections.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46709>
[<li><a href=https://deploy-preview-193--docs-kotlin.netlify.app/fundamentals/databases-collections>fundamentals/databases-collections</a></li>](https://deploy-preview-193--docs-kotlin.netlify.app/fundamentals/databases-collections/#access-a-database)
Specific section: https://deploy-preview-193--docs-kotlin.netlify.app/fundamentals/databases-collections/#access-a-database
=> DOCSP-46709 getDatbase() 404

source/fundamentals/connection/connect.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48759>
<li><a href=https://deploy-preview-212--docs-kotlin.netlify.app/fundamentals/connection/connect>fundamentals/connection/connect</a></li>
=> DOCSP-48759: docker note

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-49719
**Same changes approved in** https://github.com/mongodb/docs-java-rs/pull/130
<li><a href=https://deploy-preview-216--docs-kotlin.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-49719: connectTimeoutMS option for TLS

source/fundamentals/auth.txt, source/fundamentals/builders/aggregates.txt, source/fundamentals/builders/projections.txt, source/fundamentals/connection/network-compression.txt, source/fundamentals/crud/read-operations/sort.txt, source/fundamentals/enterprise-auth.txt, source/fundamentals/indexes.txt, source/fundamentals/stable-api.txt, source/fundamentals/time-series.txt, source/includes/mongodb-compatibility-table-kotlin.rst, source/usage-examples/bulkWrite.txt, source/usage-examples/count.txt
* DOCSP-50017 Remove EOL versions
* auth
* auth suggestion NR
* NR comments
* get rid of font on headings
(cherry picked from commit 94fd075a3dc034aaa464b665aa89094fb23bf8e5)
(cherry picked from commit 7046a65689f30a4b07a83014adc04acf0dfbe28b)
JIRA - <https://jira.mongodb.org/browse/DOCSP-50017>
<li><a href=https://deploy-preview-222--docs-kotlin.netlify.app/fundamentals/auth>fundamentals/auth</a></li><li><a href=https://deploy-preview-222--docs-kotlin.netlify.app/fundamentals/builders/aggregates>fundamentals/builders/aggregates</a></li><li><a href=https://deploy-preview-222--docs-kotlin.netlify.app/fundamentals/builders/projections>fundamentals/builders/projections</a></li><li><a …
=> [Backport V5.4] DOCSP-50017 Remove EOL mentions

source/fundamentals/auth.txt, source/fundamentals/builders/aggregates.txt, source/fundamentals/builders/projections.txt, source/fundamentals/connection/network-compression.txt, source/fundamentals/crud/read-operations/sort.txt, source/fundamentals/enterprise-auth.txt, source/fundamentals/indexes.txt, source/fundamentals/stable-api.txt, source/fundamentals/time-series.txt, source/includes/mongodb-compatibility-table-kotlin.rst, source/usage-examples/bulkWrite.txt, source/usage-examples/count.txt
* DOCSP-50017 Remove EOL versions
* auth
* auth suggestion NR
* NR comments
* get rid of font on headings
(cherry picked from commit 94fd075a3dc034aaa464b665aa89094fb23bf8e5)
(cherry picked from commit 7046a65689f30a4b07a83014adc04acf0dfbe28b)
=> DOCSP-50017 Remove EOL versions (#220) (#221)

source/fundamentals/data-formats/codecs.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-50737>
<li><a href=https://deploy-preview-236--docs-kotlin.netlify.app/fundamentals/data-formats/codecs>fundamentals/data-formats/codecs</a></li>
=> DOCSP-50737 Update Codecs Page Title
