mongodb/docs-kotlin

config/redirects
Redirect https://www.mongodb.com/docs/drivers/kotlin/coroutine/ to https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/
based on how java docs does it - https://github.com/mongodb/docs-java/blob/master/config/redirects
JIRA - n/a
Staging - n/a
=> Redirect `/` to `/current/`

.github/workflows/kotlin.yml, examples/src/test/kotlin/BuildersTest.kt, examples/src/test/kotlin/ChangeTest.kt, examples/src/test/kotlin/ConnectTest.kt, examples/src/test/kotlin/LimitTest.kt, examples/src/test/kotlin/LoggingTest.kt
Updates the GH action to run a local server. Any pending PRs will need to be updated to use `getConfig()` or the test will fail.
> NOTE: Currently, it creates a replica set with no users.
JIRA - https://jira.mongodb.org/browse/DOCSP-29415
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/no-jira-logging-import-fix/
=> (DOCSP-29415): Update GH action to run local mongoDB server

examples/src/test/kotlin/DataClassTest.kt, examples/src/test/kotlin/DatabaseCollectionsTest.kt, source/examples/generated/DataClassTest.snippet.retrieve-diff-data-class.kt, source/examples/generated/DatabaseCollectionsTest.snippet.fruit-data-class.kt, source/examples/generated/DatabaseCollectionsTest.snippet.return-type.kt, source/fundamentals/data-formats/document-data-format-data-class.txt, source/fundamentals/databases-collections.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-30063
Staging:
- [Specify return type in DB/coll page](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-30063-withDocument-method/fundamentals/databases-collections/#specify-return-type)
- [new content in data class doc format pg](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-30063-withDocument-method/fundamentals/data-formats/document-data-format-data-class/#retrieve-a-data-class)
=> DOCSP-30063: specify return type using withDocument

examples/src/test/kotlin/QueryDocumentTest.kt, source/examples/generated/QueryDocumentTest.snippet.array-filter.kt, source/examples/generated/QueryDocumentTest.snippet.comparison-filter.kt, source/examples/generated/QueryDocumentTest.snippet.element-filter.kt, source/examples/generated/QueryDocumentTest.snippet.evaluation-filter.kt, source/examples/generated/QueryDocumentTest.snippet.logical-filter.kt, source/fundamentals/auth.txt, source/fundamentals/connection.txt, source/fundamentals/connection/connect.txt, source/fundamentals/connection/connection-options.txt, source/fundamentals/crud/read-operations/change-streams.txt, source/fundamentals/crud/write-operations/insert.txt, source/includes/fundamentals-sections.rst, source/quick-reference.txt, source/quick-start.txt, source/usage-examples/updateOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-30169
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/docsp-30169-todo/
=> (DOCSP-30169): Resolve outstanding TODOs in project

snooty.toml, source/index.txt
Remove "Alpha" label and note
To be merged and deployed once Java v4.10 is released
JIRA - https://jira.mongodb.org/browse/DOCSP-30215
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/docsp-30215-alpha-label/
=> (DOCSP-30215): Remove alpha label

source/quick-start.txt
JIRA
- https://jira.mongodb.org/browse/DOCSP-30924
- https://jira.mongodb.org/browse/DA-5729
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/docsp-30924-da-article/quick-start/
=> DOCSP-30924: Add link to DevHub Getting Started tutorial

source/index.txt
- Update DevHub link on landing page to filter by language instead of a "Kotlin" keyword search (which links out to unsorted search results instead of newest content).
- Per Mohit's request, add Getting Started tutorial link to landing page Learn section
JIRA - no Jira
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/no-jira-update-devhub-link/#developer-hub
=> Update DevHub link on landing page

examples/src/test/kotlin/DocumentsTest.kt, examples/src/test/kotlin/EjsonTest.kt, examples/src/test/kotlin/UpdatesBuildersTest.kt, source/examples/generated/DocumentsTest.snippet.create-bson-document.kt, source/examples/generated/DocumentsTest.snippet.create-document.kt, source/examples/generated/DocumentsTest.snippet.retrieve-bson-document.kt, source/examples/generated/EjsonTest.snippet.custom-bson-type-conversion.kt, source/examples/generated/UpdatesBuildersTest.snippet.current-timestamp-update.kt, source/fundamentals/data-formats/document-data-format-extended-json.txt, source/fundamentals/data-formats/documents.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-30481
Staging:
- [Documents](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-30481-localdatetime/fundamentals/data-formats/documents/)
- [Extended JSON](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-30481-localdatetime/fundamentals/data-formats/document-data-format-extended-json/)
=> DOCSP-30481: replace date with LocalDateTime

examples/src/test/kotlin/BulkTest.kt, snooty.toml, source/examples/generated/BulkTest.snippet.bulk-data-model.kt, source/examples/generated/BulkTest.snippet.bulk-write-exception.kt, source/examples/generated/BulkTest.snippet.delete.kt, source/examples/generated/BulkTest.snippet.insert-one.kt, source/examples/generated/BulkTest.snippet.ordered.kt, source/examples/generated/BulkTest.snippet.replace-one.kt, source/examples/generated/BulkTest.snippet.unordered.kt, source/examples/generated/BulkTest.snippet.update-one.kt, source/fundamentals/crud/write-operations/bulk.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-30086
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-30086-bulkops-cleanup/fundamentals/crud/write-operations/bulk/)
=> DOCSP-30086: bulk ops cleanup

source/fundamentals/builders/filters.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-30873)
[Staging ](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-30873-Clarifying-Filters-on-Builders-pg/fundamentals/builders/filters/)
There was a suggestion to remove filter usage example, but I think it improves understanding for someone new to filters. Very open to suggestions however! Also my change might be a bit redundant but again I think it makes it clearer for someone who might not understand the jargon.
=> Docsp-30873: clarifying filters on builders pg

source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
[JIRA ](https://jira.mongodb.org/browse/DOCSP-30726#r1226735778)
Staging - [UpdateMany](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-39726-Usage-Example-describe-query/usage-examples/updateMany/) page, [updateOne](https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-39726-Usage-Example-describe-query/usage-examples/updateOne/) page
=> DOCSP-39726: Usage Example that describe query

source/connection-troubleshooting.txt, source/faq.txt, source/index.txt, source/issues-and-help.txt
=> DOCSP-30724: Connection Troubleshooting page

config/redirects, source/fundamentals/crud/write-operations.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/modify.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-31827
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-31827-update-titles/fundamentals/crud/write-operations/modify/
https://docs-mongodbcom-staging.corp.mongodb.com/kotlin/docsworker-xlarge/DOCSP-31827-update-titles/fundamentals/crud/write-operations/delete/
Redirects - 
Redirect 301 /docs/drivers/kotlin/coroutine/v4.10/fundamentals/crud/write-operations/change-a-document/ https://www.mongodb.com/docs/drivers/kotlin/coroutine/v4.10/fundamentals/crud/write-operations/modify/
Redirect 301 /docs/drivers/kotlin/coroutine/master/fundamentals/crud/write-operations/change-a-document/ …
=> DOCSP-31827: Update page titles

source/includes/language-compatibility-table-kotlin.rst
Note: no changes that affect format or content were made.
This PR contains a linebreak erasure to test that the API auth token that the "Copy to docs shared" GH action depends on functions correctly. The PR contain a change to the compatibility table files and be merged to trigger the GH action.
JIRA: none
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/kotlin/092123-test-shared-copy-action/compatibility/#language-compatibility
=> 092123 trivial change to test GH action that copies compat tables

.github/workflows/copy-compat-to-docs-shared.yml, source/includes/mongodb-compatibility-table-kotlin.rst
Removes rapid release version v6.1
Hope to also test the docs-shared copy GH action fixes.
JIRA - None
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/kotlin/092223-compatibility-copy/compatibility/#compatibility-table-legend
=> 092223 compatibility copy

source/fundamentals/aggregation-expression-operations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-33931
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/kotlin/DOCSP-33931-fix-agg-links/fundamentals/aggregation-expression-operations/#array-operations
=> DOCSP-33931: fix agg operator links

examples/build.gradle.kts, examples/gradle.properties, examples/src/test/kotlin/AggregatesBuilderTest.kt, source/examples/generated/AggregatesBuilderTest.snippet.vector-search-data-class.kt, source/examples/generated/AggregatesBuilderTest.snippet.vector-search.kt, source/fundamentals/builders/aggregates.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33428>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-33428-vectorsearch-builder/fundamentals/builders/aggregates/#atlas-vector-search
=> DOCSP-33428: vectorsearch builder

examples/src/test/kotlin/ChangeStreamsTest.kt, source/examples/generated/ChangeStreamsTest.snippet.split-large-change-stream.kt, source/fundamentals/crud/read-operations/change-streams.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33427>
[Staging](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-33427-changestream-split/fundamentals/crud/read-operations/change-streams/#split-large-change-stream-events)
=> DOCSP-33427: split large cs events

examples/src/test/kotlin/SocksTest.kt, source/examples/generated/SocksTest.snippet.socks-connection-string.kt, source/examples/generated/SocksTest.snippet.socks-mongoclientsettings.kt, source/fundamentals/connection.txt, source/fundamentals/connection/mongoclientsettings.txt, source/fundamentals/connection/socks5.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33426>
Staging:
- [socks5 guide](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-33426-socks5/fundamentals/connection/socks5/)
- [mongoclientsettings](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-33426-socks5/fundamentals/connection/mongoclientsettings/#socket-settings)
- [landing pg](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-33426-socks5/fundamentals/connection/)
=> DOCSP-33426: socks5 proxy server

source/fundamentals/data-formats/serialization.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-28748>
**[Staging](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-28748-bson-kotlin/fundamentals/data-formats/serialization/#customize-the-serializer-configuration:~:text=NOTE-,bson%2Dkotlin%20Dependency,-You%20can%20also)**
=> DOCSP-28748: bson-kotlin dependency

examples/src/test/kotlin/InsertTest.kt, source/examples/ServerManualCodeExamples.kt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34191> <https://jira.mongodb.org/browse/DOCSP-34193>
No staging relevant - just creating a code file.
=> DOCSP-34191 and DOCSP-34193 code examples

examples/gradle.properties, examples/src/test/kotlin/EnterpriseAuthTest.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-azure-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-azure-credential.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-callback-file.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-callback.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-gcp-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-gcp-credential.kt, source/fundamentals/connection/connection-options.txt, source/fundamentals/connection/mongoclientsettings.txt, source/fundamentals/enterprise-auth.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-39405>
Staging:
- [oidc](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-39405-v5.1-content/fundamentals/enterprise-auth/#std-label-kotlin-oidc)
- [connection options](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-39405-v5.1-content/fundamentals/connection/connection-options/#std-label-connection-options:~:text=serverMonitoringMode)
- [whats new](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-39405-v5.1-content/whats-new/#std-label-kotlin-coroutine-version-5.1)
=> DOCSP-39405: kotlin v5.1 content

examples/gradle.properties, snooty.toml, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-40728>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-40728-5.1.1-patch/whats-new/#std-label-kotlin-coroutine-version-5.1.1>
=> DOCSP-40728: v5.1.1 patch updates

examples/build.gradle.kts, examples/src/test/kotlin/CodecTest.kt, examples/src/test/kotlin/KotlinXSerializationTest.kt, examples/src/test/kotlin/TlsTest.kt, source/examples/generated/CodecTest.snippet.example-codec-2.kt, source/examples/generated/KotlinXSerializationTest.snippet.polymorphic-dataclasses.kt, source/examples/generated/KotlinXSerializationTest.snippet.polymorphic-example.kt, source/fundamentals/connection/tls.txt, source/fundamentals/data-formats/serialization.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36217>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-36217-polymorphic/fundamentals/data-formats/serialization/#polymorphic-serialization>
=> DOCSP-36217: polymorphic serialization

examples/build.gradle.kts, examples/gradle.properties, snooty.toml, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41360>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-41360-v5.1.2-patch/whats-new/#std-label-kotlin-coroutine-version-5.1.2
=> DOCSP-41360: v5.1.2 patch release

source/index.txt, source/validate-signatures.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-39555>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-39555-jvm-validate-sigs/validate-signatures/
=> DOCSP-39555: kotlin driver sig verification

examples/src/test/kotlin/AuthTest.kt, examples/src/test/kotlin/EnterpriseAuthTest.kt, examples/src/test/kotlin/MongoClientSettingsTest.kt, source/connection-troubleshooting.txt, source/examples/generated/AuthTest.snippet.default-cred-string.kt, source/examples/generated/AuthTest.snippet.default-mongo-cred.kt, source/examples/generated/AuthTest.snippet.scram-sha-1-cred.kt, source/examples/generated/AuthTest.snippet.scram-sha-1-string.kt, source/examples/generated/AuthTest.snippet.scram-sha-256-cred.kt, source/examples/generated/AuthTest.snippet.scram-sha-256-string.kt, source/examples/generated/AuthTest.snippet.x-509-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.auth-creds-gssapi.kt, source/examples/generated/EnterpriseAuthTest.snippet.gssapi-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.gssapi-properties-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.java-subject-key.kt, source/examples/generated/EnterpriseAuthTest.snippet.kerberos-subject-provider.kt, source/examples/generated/EnterpriseAuthTest.snippet.ldap-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.ldap-mongo-credential.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-azure-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-azure-credential.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-gcp-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-gcp-credential.kt, source/examples/generated/EnterpriseAuthTest.snippet.service-name-key.kt, source/examples/generated/MongoClientSettingsTest.snippet.chain-order-connection-string.kt, source/fundamentals/auth.txt, source/fundamentals/connection/connect.txt, source/fundamentals/enterprise-auth.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42514>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-42514-user-pass-plchldr/
=> DOCSP-42514: kotlin user/pass placeholders

examples/src/test/kotlin/SearchIndexesTest.kt, source/examples/generated/SearchIndexesTest.snippet.multi-search-index-create.kt, source/examples/generated/SearchIndexesTest.snippet.single-search-index-create.kt, source/fundamentals/indexes.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42282>
Staging:
- [indexes](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-42282-avs-index-type/fundamentals/indexes/#create-a-search-index)
- [whats new](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-42282-avs-index-type/whats-new/#what-s-new-in-5.2)
=> DOCSP-42282: java avs type support

source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43551>
Staging - https://deploy-preview-174--docs-kotlin.netlify.app/whats-new/#what-s-new-in-5.2
=> DOCSP-43551: json encoding v5.2

source/issues-and-help.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44292>
Staging - <https://deploy-preview-177--docs-kotlin.netlify.app/issues-and-help/>
=> DOCSP-44292: improve i&h

source/fundamentals/connection/mongoclientsettings.txt, source/fundamentals/data-formats/document-data-format-data-class.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42963>
Staging - <https://deploy-preview-178--docs-kotlin.netlify.app/>
=> Following guidance, removing nested components from tables

source/fundamentals.txt, source/fundamentals/builders.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/data-formats.txt, source/index.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/update-operations.txt
* DOCSP-44902 TOC Relabel
* DOCSP-44902 TOC Relabel
* Mike's suggestions
* 'one/many' operation changes
(cherry picked from commit 1144bde00f5ce107638a6d2664abce2ea62aad3b)
Co-authored-by: lindseymoore <71525840+lindseymoore@users.noreply.github.com>
(cherry picked from commit bc41eefcc7e17f719a9a4a50344cdab7d8ad16e1)
=> [Backport v5.1] DOCSP-44902 Shorten TOC

examples/src/test/kotlin/BulkTest.kt, examples/src/test/kotlin/ClientBulkTest.kt, source/examples/generated/ClientBulkTest.snippet.data-classes.kt, source/examples/generated/ClientBulkTest.snippet.insert-models.kt, source/examples/generated/ClientBulkTest.snippet.options.kt, source/examples/generated/ClientBulkTest.snippet.replace-models.kt, source/fundamentals/crud/write-operations/bulk.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46389>
Staging - https://deploy-preview-189--docs-kotlin.netlify.app/fundamentals/crud/write-operations/bulk/#std-label-kotlin-client-bulk-write
=> DOCSP-46389: client bw

source/fundamentals/crud/read-operations/change-streams.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46708>
<li><a href=https://deploy-preview-192--docs-kotlin.netlify.app/fundamentals/crud/read-operations/change-streams>fundamentals/crud/read-operations/change-streams</a></li>
Link in this "Example" section: https://deploy-preview-192--docs-kotlin.netlify.app/fundamentals/crud/read-operations/change-streams/#example
=> DOCSP-46708 MongoClient.watch() API 404

examples/src/test/kotlin/RetrieveDataTest.kt, source/fundamentals/aggregation.txt, source/fundamentals/crud/query-document.txt, source/fundamentals/crud/read-operations/geo.txt, source/fundamentals/crud/read-operations/retrieve.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48207>
<li><a href=https://deploy-preview-203--docs-kotlin.netlify.app/fundamentals/aggregation>fundamentals/aggregation</a></li><li><a href=https://deploy-preview-203--docs-kotlin.netlify.app/fundamentals/crud/query-document>fundamentals/crud/query-document</a></li><li><a href=https://deploy-preview-203--docs-kotlin.netlify.app/fundamentals/crud/read-operations/geo>fundamentals/crud/read-operations/geo</a></li><li><a href=https://deploy-preview-203--docs-kotlin.netlify.app/fundamentals/crud/read-operations/retrieve>fundamentals/crud/read-operations/retrieve</a></li>
=> DOCSP-48207: 404s + cleanup

examples/src/test/kotlin/EnterpriseAuthTest.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-k8s-connection-string.kt, source/examples/generated/EnterpriseAuthTest.snippet.oidc-k8s-credential.kt, source/fundamentals/enterprise-auth.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47923>
<li><a href=https://deploy-preview-205--docs-kotlin.netlify.app/fundamentals/enterprise-auth>fundamentals/enterprise-auth</a></li><li><a href=https://deploy-preview-205--docs-kotlin.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-47923: kubernetes oidc

examples/src/test/kotlin/KotlinXSerializationTest.kt, source/examples/generated/KotlinXSerializationTest.snippet.snake-case-naming.kt, source/examples/generated/KotlinXSerializationTest.snippet.snake-case-serialization.kt, source/fundamentals/data-formats/serialization.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46215>
<li><a href=https://deploy-preview-209--docs-kotlin.netlify.app/fundamentals/data-formats/serialization>fundamentals/data-formats/serialization</a></li><li><a href=https://deploy-preview-209--docs-kotlin.netlify.app/whats-new>whats-new</a></li>
=> [Kotlin CR] Support naming strategy for bson-kotlinx

source/api-documentation.txt, source/compatibility.txt, source/connection-troubleshooting.txt, source/faq.txt, source/fundamentals/aggregation-expression-operations.txt, source/fundamentals/aggregation.txt, source/fundamentals/auth.txt, source/fundamentals/builders.txt, source/fundamentals/collations.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/data-formats.txt, source/fundamentals/databases-collections.txt, source/fundamentals/indexes.txt, source/fundamentals/logging.txt, source/fundamentals/monitoring.txt, source/fundamentals/stable-api.txt, source/fundamentals/time-series.txt, source/index.txt, source/issues-and-help.txt, source/quick-reference.txt, source/quick-start.txt, source/usage-examples.txt, source/whats-new.txt
Adds missing meta descriptions generated by the Education AI Team\n\nSOURCE: https://docs.google.com/spreadsheets/d/1fdrjF4Ms9fMl96zLiLGsYD_V38rTfPLuKs5VQk4vz6E/edit?gid=1166644539
=> Add missing meta descriptions

source/fundamentals/connection.txt
Coroutine docs aren't standardized so I put the link in the most fitting spot
JIRA - <https://jira.mongodb.org/browse/DOCSP-48544>
<li><a href=https://deploy-preview-215--docs-kotlin.netlify.app/fundamentals/connection>fundamentals/connection</a></li>
=> DOCSP-48544: Add AWS Lambda link

source/fundamentals/builders.txt, source/fundamentals/builders/vector-search.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48250>
=> DOCSP-48250

source/fundamentals/builders/builders-data-classes.txt, source/fundamentals/data-formats/document-data-format-bson.txt, source/fundamentals/data-formats/serialization.txt, source/fundamentals/encrypt-fields.txt, source/includes/fundamentals/code-snippets/bson-gradle-versioned.rst, source/includes/fundamentals/code-snippets/bson-maven-versioned.rst, source/includes/fundamentals/code-snippets/crypt-gradle-versioned.rst, source/includes/fundamentals/code-snippets/crypt-maven-versioned.rst, source/includes/serialization-libs-gradle-versioned.rst, source/includes/serialization-libs-maven-versioned.rst
This will backport the following commits from `master` to `v5.4`:
- [Docsp-49013  (#226)](https://github.com/mongodb/docs-kotlin/pull/226)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> [v5.4] Docsp-49013  (#226)
